creation_rules:
  - path_regex: releases/.*/secrets\.yaml$
    encrypted_regex: '(?i)(.*token.*|.*_id$)'
    age:
      - age1hzgk40srsm6xv260h0xptaa0qqdpetegx5vjl78x9qmk9u92jagsezvequ
  
stores:
  yaml:
    indent: 2
