image: ghcr.io/cloudnative-pg/postgresql:18.6-system-trixie
enabled: false
instances: 1
bootstrap: {}
storage:
  size: 1Gi

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

secret:
  enabled: false
  name: ""
  type: Opaque
  annotations: {}
  data: {}
  stringData: {}

nameOverride: ""
fullnameOverride: ""
