prometheusSecret:
  bot_token: ENC[AES256_GCM,data:RRauqmJdIAngc0BaAWP4SvvjNvtG3QitVnLSY9/GpFv5CNWutfGX8iBkFxnWtg==,iv:q+B4vNBHhtl3trNd7XYbYMDdzP5f0gnLXo/0l0cghuQ=,tag:NXnAbYyiP2MYyJBjMFfJDA==,type:str]
  chat_id: ENC[AES256_GCM,data:s8Dq8NTYaPEDznK9S2s=,iv:yIDShAD3bx74axyciumCKhmnLomG6DD6eKaMw9C6pIQ=,tag:N5ZIb3BD4psavxMGcNae5A==,type:str]
  admin_password: ENC[AES256_GCM,data:kwE2k3wrQmg=,iv:qYbzdfm1KMmV0ndGsalTLdYzGUNwgvevooCXSTVB/dU=,tag:XUm5bROCDlW76d6w5Mq6yg==,type:str]
  admin_user: admin
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3U1pVb0FDVkEySXNRTnFG
        MVhvU0tZL1FiWHAybC85QjFpeURrOTBYSmgwCkkvUC83STZyUU5RKzhRTVh1a0do
        ZEZpdnJwclhXZDhVdnR1RFBwSUt0cG8KLS0tIHVsNFBleVhuT0ZScUo2eGpDbUQz
        MFY4QmEzUVhCYytRd0lZNHEzQ2hnemsKONAIlzI2DLl+IxulX3jKbZ1vWfgidA1m
        jxCxCGDvU0q+V0UH9eMhFvgvfJMmouVc+K09GIrEYB/ncRrHfIHaZA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hzgk40srsm6xv260h0xptaa0qqdpetegx5vjl78x9qmk9u92jagsezvequ
  encrypted_regex: (?i)(.*token.*|.*password.*|.*_id$)
  lastmodified: "2026-09-28T12:35:30Z"
  mac: ENC[AES256_GCM,data:C3fQbiqaSnFb4UmOfgl1A4NK7FnJ6OeMy8BVgCKj0fERYiTGNkTzhwpChdZdV2K5cIgqq2dEtFC8DaFLj7OWHLwlgLoLdkG3VHppCYAL8DMpnyS2cakQuCP3mXcxbwqGQD95V+Itb2HPzaXqS5LMq4/121vBKVrYcSBXX8Ljerk=,iv:6538YWWuNraX5c6CY/huFVhdfXJD8eB9rpsT/yb7kmQ=,tag:BuRhvre489zociHBUmKtEA==,type:str]
  version: 3.13.3
