image:
  repository: ghcr.io/klov148/api-lab3
  pullPolicy: IfNotPresent
  tag: "latest"

env:
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger.observability.svc.cluster.local:4318"
  OTEL_SERVICE_NAME: "api-lab3"

podLabels:
  app.kubernetes.io/component: api
  app.kubernetes.io/part-of: lab3

# Нужно для работы prometheus discovery
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: /metrics
  prometheus.io/port: "8080"

ingress:
  enabled: true
  className: "traefik"
  annotations: {}
  hosts:
    - host: api-lab3.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

nameOverride: api-lab3
fullnameOverride: api-lab3

replicaCount: 3
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi