image:
  repository: ghcr.io/klov148/api-lab3
  pullPolicy: IfNotPresent
  tag: "latest"

env:
  PGHOST: "postgres-lab3-rw"
  PGPORT: "5432"
  PGDATABASE: "app"
  PGSSLMODE: "disable"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger.observability.svc.cluster.local:4318"
  OTEL_SERVICE_NAME: "api-lab3"

secretEnv:
  PGUSER:
    name: postgres-lab3-secret
    key: username
  PGPASSWORD:
    name: postgres-lab3-secret
    key: password

podLabels:
  app.kubernetes.io/component: api
  app.kubernetes.io/part-of: shop
  app.kubernetes.io/lab: lab3

ingress:
  enabled: true
  className: "traefik"
  annotations: {}
  hosts:
    - host: api-lab3.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

nameOverride: api-lab3
fullnameOverride: api-lab3

replicaCount: 3
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
