image:
  repository: api
  pullPolicy: IfNotPresent
  tag: "1.0.0"

env:
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger.observability.svc.cluster.local:4318"
  OTEL_SERVICE_NAME: "api"

podLabels:
  app.kubernetes.io/component: api
  app.kubernetes.io/part-of: lab2-observability

# Нужно для работы prometheus discovery
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: /metrics
  prometheus.io/port: "8080"

ingress:
  enabled: true
  className: "traefik"
  annotations: {}
  hosts:
    - host: api.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

nameOverride: api
fullnameOverride: api