prometheusSecret:
  bot_token: ENC[AES256_GCM,data:Nb36CrwS9uEry7ntxaDAJcDe6FJT/BdRSlTxJ5Vqmibe5wMSKYZe/VsNjVgbGA==,iv:N6gS1j/Q6NxiNvoILJZZePkSqhvZfDgft4mE77AiZ1k=,tag:71IILv2J2p2zKOt3JFknKw==,type:str]
  chat_id: ENC[AES256_GCM,data:aZ+RaWeVV2CBAfJ70a4=,iv:X2x6yWfqe7CMKvr/A1W8yJ1INJ5egjjn1287+aaXjvQ=,tag:Mc1vl9JfBLFnpanLaguAaQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdkNLQ0xkWkZ4ODRoRTlJ
        WnJ5T0NMbElyUjMxSnRlR2JhNUdvNFAzV0V3ClZiaEMvcFVuQXFOT1RxTHRFck1k
        cnppTXRUMitoYTJRWTNHamgyR01xcUUKLS0tIDJzTXRGOHJaVDJrYTkvKzYwMlU2
        YzVQQ2ZlM2k1a21WWkthSmwvM2kyMHMKhX+ILOx8+KIjHjQNbXTVrcA4BiqJb3Or
        Wxn/7hSxmDSzIDfEs88UWVGofXScyShXkqGOMQp+r+87C3lXzgfZ1g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hzgk40srsm6xv260h0xptaa0qqdpetegx5vjl78x9qmk9u92jagsezvequ
  encrypted_regex: (?i)(.*token.*|.*_id$)
  lastmodified: "2026-09-22T17:32:12Z"
  mac: ENC[AES256_GCM,data:jJ/Lqt9HDlDPNKHaoKurXJPHKNn6Pt+fsTt30sYbr7wfEya3kYk81Tylz1lK62xquI4bSPE4uXSmAkaInLAUTysWI0KHNBKzz4eGRCx0nE7xqQ9lmcCZsPFWH5D2GOyGRChgoriOsXzJVFdXFXuJXfcDJJekA4FqzJqAiJfnYNw=,iv:qHbEyZB+Rnv8jNvG56iIGaXTgcRd2MXSc/ifIKD7hkw=,tag:3L7NKAhV2ZLida28GHAX7w==,type:str]
  version: 3.13.3
