serviceMonitor:
  enabled: false
  name: "app"
  labels: {}
  selector: {}
  endpoints: []

prometheusRule:
  enabled: false
  name: "app"
  labels: {}
  groups: []

configMap:
  enabled: false
  name: "app"
  labels: {}
  annotations: {}
  data: {}
