serviceMonitor:
  enabled: true
  name: shop
  labels:
    release: kube-prom-stack
  selector:
    matchLabels:
      app.kubernetes.io/part-of: shop
  endpoints:
    - port: http
      path: /metrics
      interval: 15s

prometheusRule:
  enabled: true
  name: shop
  labels:
    release: kube-prom-stack
  groups:
    - name: shop-alerts
      rules:
        - alert: HighErrorRate
          expr: >-
            (
              sum by (namespace, service) (
                rate(http_errors_total{namespace="api"}[5m])
              )
              /
              sum by (namespace, service) (
                rate(http_requests_total{namespace="api"}[5m])
              )
            ) > 0.5
            and
            sum by (namespace, service) (
              increase(http_requests_total{namespace="api"}[5m])
            ) >= 10
          for: 5m
          labels:
            severity: "High"
          annotations:
            summary: "{{ $labels.service }} error rate is above 50%"

        - alert: HighLatency
          expr: >-
            histogram_quantile(
              0.95,
              sum by (le, namespace, service) (
                rate(http_request_duration_seconds_bucket{
                  namespace="api"
                }[5m])
              )
            ) > 5
          for: 5m
          labels:
            severity: "High"
          annotations:
            summary: "High response latency on {{ $labels.service }}"

        - alert: ApiDown
          expr: >-
            min by (namespace, deployment) (
              kube_deployment_status_replicas_available{namespace="api"}
            ) == 0
          for: 5m
          labels:
            severity: "Critical"
          annotations:
            summary: "{{ $labels.deployment }} is DOWN"


    - name: cluster-alerts
      rules:
        - alert: NodeNotReady
          expr: >-
            group by (node, condition, status) (
              kube_node_status_condition{condition="Ready", status=~"false|unknown"} == 1
            )
          for: 5m
          labels:
            severity: "Critical"
          annotations:
            summary: "{{ $labels.node }} not ready"
            
        - alert: APIServerDown
          expr: >-
            sum(up{job="apiserver"}) == 0
            or absent(up{job="apiserver"})
          for: 5m
          labels:
            severity: "Critical"
          annotations:
            summary: "No API server metrics endpoint is reachable"

        - alert: CoreDNSDown
          expr: >-
            sum(up{job="coredns"}) == 0
            or absent(up{job="coredns"})
          for: 5m
          labels:
            severity: "Critical"
          annotations:
            summary: "No CoreDNS metrics endpoint is reachable"
