secret:
  stringData:
    username: app
    password: ENC[AES256_GCM,data:RGa/cg6upCTd,iv:cTcw473NYQ3PKBC3r3qqYiJCFCg3cNrRnsHnRl4bFjI=,tag:ovTTM9HvcDpADs5o6a20Eg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSODd3UDByc0ZXT0UvT3Uw
        emowbUtrUnVUYWlhdXViSDZKTGJNZVlCeUhNCjB1YUN3ME9YT05Zb0VnMUZnQTlw
        L3lMVkc2MXJ6M0pNVHJBQitMV1ZQcUUKLS0tIGY5TGUrdWwzVjVodUYySEN2M0Nk
        d3ZBWVJNRG55OVdaaSs0Q1I5dk95bVkKfiGxVCh65ynWq45DxGXULnVrgMeUgEQD
        eB/MTML5EUsQ6wi67hl3zsDrZJ2QzlY1N0Qne13NwUmJL56Qs90LLg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hzgk40srsm6xv260h0xptaa0qqdpetegx5vjl78x9qmk9u92jagsezvequ
  encrypted_regex: (?i)(.*token.*|.*password.*|.*_id$)
  lastmodified: "2026-09-27T16:32:44Z"
  mac: ENC[AES256_GCM,data:RqmmG+s/21to+UWsFEob2ckqnv1788y47LYRbbyJ8rNa8anZRJ2LD85UIe9Fh1HZD8Ho30nNPObfjMdlpYsVllByBZ0q5D9EEoJMnIMmO5E7zEyOOS+zu1hqTPgHSmgqquR4It6uen/5QLWy7bReTPAKd5p+hMvYE9ilxw+ufRc=,iv:holDnI821/GuOH1SNeqSAId+bILebEQ6S7Qzrj7h/60=,tag:9XDyRuG1xf9tuOzS5Z0iIA==,type:str]
  version: 3.13.3
