enabled: true
instances: 1
bootstrap:
  initdb:
    database: app
    owner: app
    secret:
      name: postgres-lab3-secret
storage:
  size: 1Gi
  storageClass: local-path

resources:
  limits:
    cpu: "1"
    memory: 512Mi
  requests:
    cpu: "1"
    memory: 512Mi

priorityClass:
  enabled: true
  value: 100000
  globalDefault: false
  preemptionPolicy: PreemptLowerPriority
  description: High priority for the critical PostgreSQL path

secret:
  enabled: true
  name: postgres-lab3-secret
  type: kubernetes.io/basic-auth

fullnameOverride: postgres-lab3
