{{- if .Values.enabled -}}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  instances: {{ .Values.instances }}
  imageName: {{ .Values.image }}
  {{- with .Values.bootstrap }}
  bootstrap:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.storage }}
  storage:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
